import { StoreData } from '@/types/store';
import { storeAnalysis } from '@/lib/flow-operating-engine';
import { DEFAULT_FLOW_NOTIFICATION_PREFERENCES, FlowNotificationPreferences, isTimeInQuietHours } from '@/lib/notification-preferences';
export interface FlowCheckIn { id: string; title: string; body: string; tone: 'info'|'success'|'warning'|'danger'; priority: number; action?: string; }
const LAST_KEY = 'storeflow_flow_checkins_v1'; const QUIET_KEY = 'storeflow_flow_checkins_quiet'; const PREF_KEY = 'storeflow_notification_preferences_v1';
function today() { return new Date().toISOString().slice(0, 10); }
function seen(id: string) { try { return JSON.parse(localStorage.getItem(LAST_KEY) || '{}')[id] === today(); } catch { return false; } }
function markSeen(id: string) { try { const v = JSON.parse(localStorage.getItem(LAST_KEY) || '{}'); v[id] = today(); localStorage.setItem(LAST_KEY, JSON.stringify(v)); } catch {} }
function prefs(): FlowNotificationPreferences { try { return { ...DEFAULT_FLOW_NOTIFICATION_PREFERENCES, ...JSON.parse(localStorage.getItem(PREF_KEY) || '{}') }; } catch { return DEFAULT_FLOW_NOTIFICATION_PREFERENCES; } }
function categoryAllowed(check: FlowCheckIn, p: FlowNotificationPreferences) { if (!p.enabled || !p.flowCheckins) return false; if (check.id === 'debts') return p.debtReminders; return p.businessInsights; }
export function getFlowCheckIns(store: StoreData): FlowCheckIn[] { const a = storeAnalysis(store); const out: FlowCheckIn[] = []; if (a.out.length) out.push({id:'out-of-stock',title:'Quick stock check',body:`${a.out.length} product${a.out.length===1?'':'s'} ${a.out.length===1?'is':'are'} out of stock. Should I show you which ones?`,tone:'danger',priority:100,action:'inventory'}); else if (a.low.length) out.push({id:'low-stock',title:'Before the day gets busy…',body:`${a.low.length} product${a.low.length===1?'':'s'} ${a.low.length===1?'is':'are'} running low. Want to check them now?`,tone:'warning',priority:90,action:'inventory'}); if (a.debt>0) out.push({id:'debts',title:'One thing to check',body:`You have ₦${Math.round(a.debt).toLocaleString()} in outstanding customer balances. Want to see who owes you?`,tone:'warning',priority:70,action:'customers'}); if (a.underpriced.length) out.push({id:'pricing',title:'I noticed something',body:`${a.underpriced.length} product${a.underpriced.length===1?'':'s'} have a thin margin. Want me to show you which ones?`,tone:'warning',priority:60,action:'pricing'}); if (a.dead.length) out.push({id:'dead-stock',title:'A small opportunity',body:'Some stock has not moved in 30 days. Want to see what is sitting on the shelf?',tone:'info',priority:50,action:'inventory'}); if (!out.length&&a.revenue7>0) out.push({id:'positive-checkin',title:'Nice work today',body:`Your store has made ₦${Math.round(a.revenue7).toLocaleString()} in the last 7 days. Want a quick look at what is driving it?`,tone:'success',priority:20,action:'sales'}); return out.sort((x,y)=>y.priority-x.priority).filter(x=>!seen(x.id)); }
export function getNextFlowCheckIn(store: StoreData) { return getFlowCheckIns(store)[0] || null; }
export async function requestFlowNotificationPermission() { if (!('Notification' in window)) return 'unsupported' as const; if (Notification.permission==='granted') return 'granted' as const; if (Notification.permission==='denied') return 'denied' as const; return Notification.requestPermission(); }
export function notifyFlowCheckIn(check: FlowCheckIn) { const p=prefs(); const critical=check.tone==='danger'; if (!categoryAllowed(check,p)) return false; if (p.quietHoursEnabled && isTimeInQuietHours(new Date(),p.quietStart,p.quietEnd) && !(critical && p.criticalAlerts)) return false; if (!('Notification' in window)||Notification.permission!=='granted') return false; try { new Notification(`Flow · ${check.title}`,{body:check.body,tag:`storeflow-${check.id}`,silent:!p.sounds}); markSeen(check.id); return true; } catch { return false; } }
export function markFlowCheckInSeen(id:string){markSeen(id);} export function setCheckInsQuiet(enabled:boolean){try{localStorage.setItem(QUIET_KEY,enabled?'1':'0');}catch{}} export function checkInsQuiet(){try{return localStorage.getItem(QUIET_KEY)==='1';}catch{return false;}}
