import { StoreData } from '@/types/store';
import { getDashboardStats, getTopSellers } from '@/lib/store-data';

// ─── Share Performance Summary ──────────────────────────────────────────────
// Short and curated — meant to be sent to a partner/accountant/yourself via
// WhatsApp or the share sheet. Deliberately does NOT list every product or
// every sale (that used to make the previous version far too long to be
// useful as a quick share). Full data belongs in Raw Export instead.
export function generatePerformanceSummary(store: StoreData): string {
  const stats = getDashboardStats(store);
  const topSellers = getTopSellers(store, 5);
  const profile = store.profile;

  let r = `📊 PERFORMANCE SUMMARY\n`;
  r += `==============================\n`;
  r += `${store.storeName}\n`;
  if (profile?.location) r += `📍 ${profile.location}\n`;
  r += `📅 ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
  r += `==============================\n\n`;

  r += `💰 OVERVIEW\n`;
  r += `Gross Revenue: ₦${stats.totalRevenue.toLocaleString()}\n`;
  r += `Total Expenses: ₦${stats.totalExpenses.toLocaleString()}\n`;
  r += `Net Income: ₦${stats.netIncome.toLocaleString()}\n`;
  r += `Profit: ₦${stats.totalProfit.toLocaleString()}\n`;
  r += `Inventory Value: ₦${stats.inventoryValue.toLocaleString()}\n`;
  r += `Total Sales: ${stats.totalSales}\n`;
  r += `Products: ${stats.totalProducts}\n\n`;

  if (topSellers.length > 0) {
    r += `🏆 TOP 5 SELLERS\n------------------------------\n`;
    topSellers.forEach((t, i) => {
      r += `${i + 1}. ${t.name} — ${t.totalSold} units (₦${t.revenue.toLocaleString()})\n`;
    });
    r += `\n`;
  }

  // Short expense breakdown by category — a few lines, not an itemized list
  const expenseByCategory = new Map<string, number>();
  (store.expenses || []).forEach(e => {
    expenseByCategory.set(e.category, (expenseByCategory.get(e.category) || 0) + e.amount);
  });
  if (expenseByCategory.size > 0) {
    r += `🧾 EXPENSES BY CATEGORY\n------------------------------\n`;
    Array.from(expenseByCategory.entries())
      .sort((a, b) => b[1] - a[1])
      .forEach(([cat, amt]) => {
        r += `${cat}: ₦${amt.toLocaleString()}\n`;
      });
    r += `\n`;
  }

  if (stats.lowStockProducts.length > 0) {
    r += `⚠️ LOW STOCK (${stats.lowStockProducts.length})\n------------------------------\n`;
    stats.lowStockProducts.slice(0, 10).forEach(p => {
      r += `${p.name}: only ${p.quantity} left!\n`;
    });
    if (stats.lowStockProducts.length > 10) r += `+${stats.lowStockProducts.length - 10} more\n`;
  }

  r += `\n==============================\nGenerated by StoreFlow\n`;
  return r;
}

// ─── Raw Export: complete text version ──────────────────────────────────────
// Every record, not a curated summary. This is the "give me everything" export.
export function generateFullTextReport(store: StoreData): string {
  const stats = getDashboardStats(store);
  const profile = store.profile;
  const lines: string[] = [];

  lines.push(`📋 FULL STORE DATA EXPORT`);
  lines.push(`==============================`);
  lines.push(`${store.storeName}`);
  if (profile?.location) lines.push(`📍 ${profile.location}`);
  lines.push(`📅 ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`);
  lines.push(`==============================\n`);

  lines.push(`💰 OVERVIEW`);
  lines.push(`Gross Revenue: ₦${stats.totalRevenue.toLocaleString()}`);
  lines.push(`Total Expenses: ₦${stats.totalExpenses.toLocaleString()}`);
  lines.push(`Net Income: ₦${stats.netIncome.toLocaleString()}`);
  lines.push(`Profit: ₦${stats.totalProfit.toLocaleString()}`);
  lines.push(`Inventory Value: ₦${stats.inventoryValue.toLocaleString()}`);
  lines.push(`Cash Balance: ₦${(store.cashBalance || 0).toLocaleString()}`);
  lines.push(`Bank Balance: ₦${(store.bankBalance || 0).toLocaleString()}`);
  lines.push(`Wallet Balance: ₦${(store.walletBalance || 0).toLocaleString()}`);
  lines.push(`Liabilities: ₦${(store.liabilities || 0).toLocaleString()}\n`);

  lines.push(`🏪 ALL PRODUCTS (${store.products.length})`);
  lines.push(`------------------------------`);
  store.products.forEach(p => {
    lines.push(`${p.name} | ${p.category} | Cost ₦${p.costPrice} | Sell ₦${p.sellingPrice} | Qty ${p.quantity} | Value ₦${(p.costPrice * p.quantity).toLocaleString()}`);
  });
  lines.push('');

  lines.push(`💵 ALL SALES (${store.sales.length})`);
  lines.push(`------------------------------`);
  store.sales.forEach(s => {
    lines.push(`${new Date(s.date).toLocaleDateString()} | ${s.productName} | Qty ${s.quantity} | ₦${s.unitPrice} each | Total ₦${s.total} | Profit ₦${s.profit}${s.paymentMethod ? ` | ${s.paymentMethod}` : ''}`);
  });
  lines.push('');

  const expenses = store.expenses || [];
  lines.push(`🧾 ALL EXPENSES (${expenses.length})`);
  lines.push(`------------------------------`);
  expenses.forEach(e => {
    lines.push(`${new Date(e.date).toLocaleDateString()} | ${e.category} | ₦${e.amount.toLocaleString()}${e.note ? ` | ${e.note}` : ''}`);
  });
  lines.push('');

  const restocks = store.restocks || [];
  if (restocks.length > 0) {
    lines.push(`📦 ALL RESTOCKS (${restocks.length})`);
    lines.push(`------------------------------`);
    restocks.forEach(r => {
      lines.push(`${new Date(r.date).toLocaleDateString()} | ${r.productName} | Qty ${r.quantity} | ₦${r.costPrice} each | Total ₦${r.total} | Funded: ${r.funding || 'balance'}`);
    });
    lines.push('');
  }

  const loans = store.loans || [];
  if (loans.length > 0) {
    lines.push(`🏦 ALL LOANS (${loans.length})`);
    lines.push(`------------------------------`);
    loans.forEach(l => {
      lines.push(`${new Date(l.date).toLocaleDateString()} | ${l.source} | ₦${l.amount.toLocaleString()} | ${l.status}${l.dueDate ? ` | Due ${new Date(l.dueDate).toLocaleDateString()}` : ''}`);
    });
    lines.push('');
  }

  const investments = store.investments || [];
  if (investments.length > 0) {
    lines.push(`💼 ALL INVESTMENTS (${investments.length})`);
    lines.push(`------------------------------`);
    investments.forEach(i => {
      lines.push(`${new Date(i.date).toLocaleDateString()} | ${i.type} | ₦${i.amount.toLocaleString()}${i.note ? ` | ${i.note}` : ''}`);
    });
    lines.push('');
  }

  const withdrawals = store.withdrawals || [];
  if (withdrawals.length > 0) {
    lines.push(`💸 ALL WITHDRAWALS (${withdrawals.length})`);
    lines.push(`------------------------------`);
    withdrawals.forEach(w => {
      lines.push(`${new Date(w.date).toLocaleDateString()} | ₦${w.amount.toLocaleString()}${w.note ? ` | ${w.note}` : ''}`);
    });
    lines.push('');
  }

  const customers = store.customers || [];
  if (customers.length > 0) {
    lines.push(`👥 ALL CUSTOMERS (${customers.length})`);
    lines.push(`------------------------------`);
    customers.forEach(c => {
      lines.push(`${c.name} | ${c.phone} | Purchases ₦${c.totalPurchases.toLocaleString()} | Owes ₦${c.outstandingDebt.toLocaleString()} | Points ${c.loyaltyPoints}`);
    });
    lines.push('');
  }

  const pending = store.pendingPayments || [];
  if (pending.length > 0) {
    lines.push(`⏳ ALL PENDING PAYMENTS (${pending.length})`);
    lines.push(`------------------------------`);
    pending.forEach(p => {
      lines.push(`${p.customerName} | Total ₦${p.total.toLocaleString()} | Paid ₦${p.paid.toLocaleString()} | Balance ₦${p.balance.toLocaleString()} | ${p.status}`);
    });
    lines.push('');
  }

  lines.push(`==============================`);
  lines.push(`Generated by StoreFlow`);
  return lines.join('\n');
}

// ─── Raw Export: complete CSV version ───────────────────────────────────────
// One CSV file, multiple tables stacked with headers — every record the app
// tracks, not just Products and Sales like before.
export function generateFullCSV(store: StoreData): string {
  const esc = (v: any) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  let csv = '';

  csv += 'PRODUCTS\n';
  csv += 'Name,Category,Cost Price,Selling Price,Quantity,Value,Restock Count\n';
  store.products.forEach(p => {
    csv += `${esc(p.name)},${esc(p.category)},${p.costPrice},${p.sellingPrice},${p.quantity},${p.costPrice * p.quantity},${p.restock_count || 0}\n`;
  });

  csv += '\nSALES\n';
  csv += 'Date,Product,Quantity,Unit Price,Total,Profit,Payment Method\n';
  store.sales.forEach(s => {
    csv += `${new Date(s.date).toLocaleDateString()},${esc(s.productName)},${s.quantity},${s.unitPrice},${s.total},${s.profit},${esc(s.paymentMethod || '')}\n`;
  });

  csv += '\nEXPENSES\n';
  csv += 'Date,Category,Amount,Note\n';
  (store.expenses || []).forEach(e => {
    csv += `${new Date(e.date).toLocaleDateString()},${esc(e.category)},${e.amount},${esc(e.note || '')}\n`;
  });

  csv += '\nRESTOCKS\n';
  csv += 'Date,Product,Quantity,Cost Price,Total,Funding\n';
  (store.restocks || []).forEach(r => {
    csv += `${new Date(r.date).toLocaleDateString()},${esc(r.productName)},${r.quantity},${r.costPrice},${r.total},${esc(r.funding || 'balance')}\n`;
  });

  csv += '\nLOANS\n';
  csv += 'Date,Source,Amount,Status,Due Date,Note\n';
  (store.loans || []).forEach(l => {
    csv += `${new Date(l.date).toLocaleDateString()},${esc(l.source)},${l.amount},${esc(l.status)},${l.dueDate ? new Date(l.dueDate).toLocaleDateString() : ''},${esc(l.note || '')}\n`;
  });

  csv += '\nINVESTMENTS\n';
  csv += 'Date,Type,Amount,Source,Note\n';
  (store.investments || []).forEach(i => {
    csv += `${new Date(i.date).toLocaleDateString()},${esc(i.type)},${i.amount},${esc(i.source || '')},${esc(i.note || '')}\n`;
  });

  csv += '\nWITHDRAWALS\n';
  csv += 'Date,Amount,Note\n';
  (store.withdrawals || []).forEach(w => {
    csv += `${new Date(w.date).toLocaleDateString()},${w.amount},${esc(w.note || '')}\n`;
  });

  csv += '\nCUSTOMERS\n';
  csv += 'Name,Phone,Total Purchases,Outstanding Debt,Loyalty Points\n';
  (store.customers || []).forEach(c => {
    csv += `${esc(c.name)},${esc(c.phone)},${c.totalPurchases},${c.outstandingDebt},${c.loyaltyPoints}\n`;
  });

  csv += '\nPENDING PAYMENTS\n';
  csv += 'Customer,Total,Paid,Balance,Status,Due Date\n';
  (store.pendingPayments || []).forEach(p => {
    csv += `${esc(p.customerName)},${p.total},${p.paid},${p.balance},${esc(p.status)},${p.dueDate ? new Date(p.dueDate).toLocaleDateString() : ''}\n`;
  });

  return csv;
}
