import { useState } from 'react';
import { StoreData } from '@/types/store';
import { getDashboardStats, getTopSellers } from '@/lib/store-data';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

interface DashboardProps {
  store: StoreData;
  onNavigate: (tab: 'inventory', lowStock?: boolean) => void;
}

type BreakdownType = 'revenue' | 'profit' | 'inventory' | 'sales' | null;

export default function Dashboard({ store, onNavigate }: DashboardProps) {
  const stats = getDashboardStats(store);
  const topSellers = getTopSellers(store, 5);
  const [activeBreakdown, setActiveBreakdown] = useState<BreakdownType>(null);

  const toggleBreakdown = (type: BreakdownType) => {
    setActiveBreakdown(prev => prev === type ? null : type);
  };

  // Generate manager performance report text
  const generateReport = () => {
    const profile = store.profile;
    let report = `📊 PERFORMANCE REPORT\n`;
    report += `==============================\n`;
    report += `${store.storeName}\n`;
    if (profile?.location) report += `📍 ${profile.location}\n`;
    report += `📅 ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
    report += `==============================\n\n`;

    report += `💰 OVERVIEW\n`;
    report += `Revenue: ₦${stats.totalRevenue.toLocaleString()}\n`;
    report += `Profit: ₦${stats.totalProfit.toLocaleString()}\n`;
    report += `Inventory Value: ₦${stats.inventoryValue.toLocaleString()}\n`;
    report += `Total Sales: ${stats.totalSales}\n`;
    report += `Products: ${stats.totalProducts}\n`;
    report += `Low Stock Items: ${stats.lowStockProducts.length}\n\n`;

    // Sold items breakdown
    const soldMap = new Map<string, { name: string; qty: number; revenue: number; profit: number }>();
    store.sales.forEach(s => {
      const existing = soldMap.get(s.productId) || { name: s.productName, qty: 0, revenue: 0, profit: 0 };
      existing.qty += s.quantity;
      existing.revenue += s.total;
      existing.profit += s.profit;
      soldMap.set(s.productId, existing);
    });

    if (soldMap.size > 0) {
      report += `📦 SOLD ITEMS\n`;
      report += `------------------------------\n`;
      Array.from(soldMap.values())
        .sort((a, b) => b.revenue - a.revenue)
        .forEach(item => {
          report += `${item.name}: ${item.qty} sold — ₦${item.revenue.toLocaleString()} (profit: ₦${item.profit.toLocaleString()})\n`;
        });
      report += `\n`;
    }

    // Remaining inventory
    report += `🏪 REMAINING INVENTORY\n`;
    report += `------------------------------\n`;
    store.products
      .filter(p => p.quantity > 0)
      .sort((a, b) => b.quantity - a.quantity)
      .forEach(p => {
        report += `${p.name}: ${p.quantity} left (₦${p.sellingPrice.toLocaleString()} each)\n`;
      });

    // Low stock warning
    if (stats.lowStockProducts.length > 0) {
      report += `\n⚠️ LOW STOCK ALERT\n`;
      report += `------------------------------\n`;
      stats.lowStockProducts.forEach(p => {
        report += `${p.name}: only ${p.quantity} left!\n`;
      });
    }

    // Top sellers
    if (topSellers.length > 0) {
      report += `\n🏆 TOP SELLERS\n`;
      report += `------------------------------\n`;
      topSellers.forEach((t, i) => {
        report += `${i + 1}. ${t.name} — ${t.totalSold} units (₦${t.revenue.toLocaleString()})\n`;
      });
    }

    report += `\n==============================\n`;
    report += `Generated by StoreFlow\n`;
    return report;
  };

  const handleShareReport = async () => {
    const text = generateReport();
    if (navigator.share) {
      try {
        await navigator.share({ title: `Performance Report - ${store.storeName}`, text });
      } catch { /* cancelled */ }
    } else {
      await navigator.clipboard.writeText(text);
    }
  };

  const handleWhatsAppReport = () => {
    const text = encodeURIComponent(generateReport());
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  // Breakdown data builders
  const getRevenueBreakdown = () => {
    const map = new Map<string, { name: string; revenue: number; qty: number }>();
    store.sales.forEach(s => {
      const existing = map.get(s.productId) || { name: s.productName, revenue: 0, qty: 0 };
      existing.revenue += s.total;
      existing.qty += s.quantity;
      map.set(s.productId, existing);
    });
    return Array.from(map.values()).sort((a, b) => b.revenue - a.revenue);
  };

  const getProfitBreakdown = () => {
    const map = new Map<string, { name: string; profit: number; margin: number }>();
    store.sales.forEach(s => {
      const product = store.products.find(p => p.id === s.productId);
      const existing = map.get(s.productId) || { name: s.productName, profit: 0, margin: 0 };
      existing.profit += s.profit;
      if (product) existing.margin = Math.round(((product.sellingPrice - product.costPrice) / product.costPrice) * 100);
      map.set(s.productId, existing);
    });
    return Array.from(map.values()).sort((a, b) => b.profit - a.profit);
  };

  const getInventoryBreakdown = () => {
    return [...store.products]
      .map(p => ({ name: p.name, quantity: p.quantity, value: p.costPrice * p.quantity, category: p.category }))
      .sort((a, b) => b.value - a.value);
  };

  const getSalesBreakdown = () => {
    // Group by date
    const map = new Map<string, { date: string; count: number; total: number }>();
    store.sales.forEach(s => {
      const dateKey = new Date(s.date).toLocaleDateString();
      const existing = map.get(dateKey) || { date: dateKey, count: 0, total: 0 };
      existing.count += 1;
      existing.total += s.total;
      map.set(dateKey, existing);
    });
    return Array.from(map.values()).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  };

  const cards = [
    { label: 'Revenue', value: `₦${stats.totalRevenue.toLocaleString()}`, color: 'text-primary', type: 'revenue' as BreakdownType },
    { label: 'Profit', value: `₦${stats.totalProfit.toLocaleString()}`, color: 'text-success', type: 'profit' as BreakdownType },
    { label: 'Inventory Value', value: `₦${stats.inventoryValue.toLocaleString()}`, color: 'text-primary', type: 'inventory' as BreakdownType },
    { label: 'Total Sales', value: stats.totalSales.toString(), color: 'text-foreground', type: 'sales' as BreakdownType },
    { label: 'Products', value: stats.totalProducts.toString(), color: 'text-foreground', type: null },
  ];

  return (
    <div className="animate-fade-in space-y-4">
      {/* Share Report Button */}
      <div className="flex gap-2">
        <button
          onClick={handleShareReport}
          className="flex-1 flex items-center justify-center gap-2 p-3 rounded-lg bg-primary/10 border border-primary/20 text-primary font-display font-semibold hover:bg-primary/20 transition-colors text-sm"
        >
          📤 Share Performance Report
        </button>
        <button
          onClick={handleWhatsAppReport}
          className="p-3 rounded-lg bg-success/10 border border-success/20 text-success font-display font-semibold hover:bg-success/20 transition-colors text-sm"
        >
          💬
        </button>
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        {cards.map(c => (
          <button
            key={c.label}
            onClick={() => c.type && toggleBreakdown(c.type)}
            className={`p-4 rounded-xl bg-card border text-left transition-colors ${
              activeBreakdown === c.type && c.type
                ? 'border-primary/50 bg-primary/5'
                : 'border-border hover:border-primary/30'
            }`}
          >
            <p className="text-xs text-muted-foreground mb-1">
              {c.label} {c.type && (activeBreakdown === c.type ? '▲' : '▼')}
            </p>
            <p className={`font-display font-bold text-xl ${c.color}`}>{c.value}</p>
          </button>
        ))}
        <button
          onClick={() => onNavigate('inventory', true)}
          className="p-4 rounded-xl bg-card border border-warning/30 hover:border-warning/60 transition-colors text-left"
        >
          <p className="text-xs text-muted-foreground mb-1">Low Stock ⚠</p>
          <p className="font-display font-bold text-xl text-warning">{stats.lowStockProducts.length}</p>
          <p className="text-[10px] text-muted-foreground mt-1">Tap to view →</p>
        </button>
      </div>

      {/* Breakdown Panel */}
      {activeBreakdown === 'revenue' && (
        <div className="p-4 rounded-xl bg-card border border-border space-y-2 animate-fade-in">
          <h3 className="font-display font-bold text-sm text-primary">Revenue Breakdown</h3>
          {getRevenueBreakdown().length === 0 ? (
            <p className="text-sm text-muted-foreground">No sales yet</p>
          ) : (
            <div className="space-y-1.5 max-h-64 overflow-y-auto">
              {getRevenueBreakdown().map((item, i) => (
                <div key={i} className="flex justify-between items-center p-2 rounded-lg bg-surface-2 text-sm">
                  <div>
                    <span className="text-foreground font-medium">{item.name}</span>
                    <span className="text-muted-foreground ml-2 text-xs">{item.qty} sold</span>
                  </div>
                  <span className="text-primary font-bold">₦{item.revenue.toLocaleString()}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {activeBreakdown === 'profit' && (
        <div className="p-4 rounded-xl bg-card border border-border space-y-2 animate-fade-in">
          <h3 className="font-display font-bold text-sm text-success">Profit Breakdown</h3>
          {getProfitBreakdown().length === 0 ? (
            <p className="text-sm text-muted-foreground">No sales yet</p>
          ) : (
            <div className="space-y-1.5 max-h-64 overflow-y-auto">
              {getProfitBreakdown().map((item, i) => (
                <div key={i} className="flex justify-between items-center p-2 rounded-lg bg-surface-2 text-sm">
                  <div>
                    <span className="text-foreground font-medium">{item.name}</span>
                    <span className="text-muted-foreground ml-2 text-xs">{item.margin}% margin</span>
                  </div>
                  <span className="text-success font-bold">₦{item.profit.toLocaleString()}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {activeBreakdown === 'inventory' && (
        <div className="p-4 rounded-xl bg-card border border-border space-y-2 animate-fade-in">
          <h3 className="font-display font-bold text-sm text-primary">Inventory Breakdown</h3>
          <div className="space-y-1.5 max-h-64 overflow-y-auto">
            {getInventoryBreakdown().map((item, i) => (
              <div key={i} className="flex justify-between items-center p-2 rounded-lg bg-surface-2 text-sm">
                <div>
                  <span className="text-foreground font-medium">{item.name}</span>
                  <span className="text-muted-foreground ml-2 text-xs">{item.quantity} units • {item.category}</span>
                </div>
                <span className="text-primary font-bold">₦{item.value.toLocaleString()}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {activeBreakdown === 'sales' && (
        <div className="p-4 rounded-xl bg-card border border-border space-y-2 animate-fade-in">
          <h3 className="font-display font-bold text-sm">Sales by Day</h3>
          {getSalesBreakdown().length === 0 ? (
            <p className="text-sm text-muted-foreground">No sales yet</p>
          ) : (
            <div className="space-y-1.5 max-h-64 overflow-y-auto">
              {getSalesBreakdown().map((day, i) => (
                <div key={i} className="flex justify-between items-center p-2 rounded-lg bg-surface-2 text-sm">
                  <div>
                    <span className="text-foreground font-medium">{day.date}</span>
                    <span className="text-muted-foreground ml-2 text-xs">{day.count} transactions</span>
                  </div>
                  <span className="text-primary font-bold">₦{day.total.toLocaleString()}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {topSellers.length > 0 && (
        <div className="p-4 rounded-xl bg-card border border-border">
          <h3 className="font-display font-bold mb-3">Top Sellers</h3>
          <div className="h-[200px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={topSellers} layout="vertical" margin={{ left: 0, right: 10 }}>
                <XAxis type="number" tick={{ fill: 'hsl(240 5% 50%)', fontSize: 11 }} />
                <YAxis
                  type="category"
                  dataKey="name"
                  width={120}
                  tick={{ fill: 'hsl(45 5% 85%)', fontSize: 11 }}
                />
                <Tooltip
                  contentStyle={{ background: 'hsl(240 10% 10%)', border: '1px solid hsl(240 8% 18%)', borderRadius: 8, fontSize: 12 }}
                  labelStyle={{ color: 'hsl(45 90% 61%)' }}
                  formatter={(value: number) => [`${value} units`, 'Sold']}
                />
                <Bar dataKey="totalSold" fill="hsl(45, 90%, 61%)" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}
    </div>
  );
}