import { useState, useMemo } from 'react';
import { StoreData } from '@/types/store';
import { getDashboardStats, getTopSellers } from '@/lib/store-data';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, CartesianGrid } from 'recharts';

interface DashboardProps {
  store: StoreData;
  onNavigate: (tab: 'inventory', lowStock?: boolean) => void;
}

type BreakdownType = 'revenue' | 'profit' | 'inventory' | 'sales' | null;
type DateRange = 'today' | 'week' | 'month' | 'all' | 'custom';

export default function Dashboard({ store, onNavigate }: DashboardProps) {
  const stats = getDashboardStats(store);
  const topSellers = getTopSellers(store, 5);
  const [activeBreakdown, setActiveBreakdown] = useState<BreakdownType>(null);
  const [salesRange, setSalesRange] = useState<DateRange>('all');
  const [customStart, setCustomStart] = useState('');
  const [customEnd, setCustomEnd] = useState('');

  const toggleBreakdown = (type: BreakdownType) => {
    setActiveBreakdown(prev => prev === type ? null : type);
  };

  // Generate manager performance report text
  const generateReport = () => {
    const profile = store.profile;
    let report = `📊 PERFORMANCE REPORT\n`;
    report += `==============================\n`;
    report += `${store.storeName}\n`;
    if (profile?.location) report += `📍 ${profile.location}\n`;
    report += `📅 ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
    report += `==============================\n\n`;

    report += `💰 OVERVIEW\n`;
    report += `Revenue: ₦${stats.totalRevenue.toLocaleString()}\n`;
    report += `Profit: ₦${stats.totalProfit.toLocaleString()}\n`;
    report += `Inventory Value: ₦${stats.inventoryValue.toLocaleString()}\n`;
    report += `Total Sales: ${stats.totalSales}\n`;
    report += `Products: ${stats.totalProducts}\n`;
    report += `Low Stock Items: ${stats.lowStockProducts.length}\n\n`;

    // Sold items breakdown
    const soldMap = new Map<string, { name: string; qty: number; revenue: number; profit: number }>();
    store.sales.forEach(s => {
      const existing = soldMap.get(s.productId) || { name: s.productName, qty: 0, revenue: 0, profit: 0 };
      existing.qty += s.quantity;
      existing.revenue += s.total;
      existing.profit += s.profit;
      soldMap.set(s.productId, existing);
    });

    if (soldMap.size > 0) {
      report += `📦 SOLD ITEMS\n`;
      report += `------------------------------\n`;
      Array.from(soldMap.values())
        .sort((a, b) => b.revenue - a.revenue)
        .forEach(item => {
          report += `${item.name}: ${item.qty} sold — ₦${item.revenue.toLocaleString()} (profit: ₦${item.profit.toLocaleString()})\n`;
        });
      report += `\n`;
    }

    // Remaining inventory
    report += `🏪 REMAINING INVENTORY\n`;
    report += `------------------------------\n`;
    store.products
      .filter(p => p.quantity > 0)
      .sort((a, b) => b.quantity - a.quantity)
      .forEach(p => {
        report += `${p.name}: ${p.quantity} left (₦${p.sellingPrice.toLocaleString()} each)\n`;
      });

    // Low stock warning
    if (stats.lowStockProducts.length > 0) {
      report += `\n⚠️ LOW STOCK ALERT\n`;
      report += `------------------------------\n`;
      stats.lowStockProducts.forEach(p => {
        report += `${p.name}: only ${p.quantity} left!\n`;
      });
    }

    // Top sellers
    if (topSellers.length > 0) {
      report += `\n🏆 TOP SELLERS\n`;
      report += `------------------------------\n`;
      topSellers.forEach((t, i) => {
        report += `${i + 1}. ${t.name} — ${t.totalSold} units (₦${t.revenue.toLocaleString()})\n`;
      });
    }

    report += `\n==============================\n`;
    report += `Generated by StoreFlow\n`;
    return report;
  };

  const handleShareReport = async () => {
    const text = generateReport();
    if (navigator.share) {
      try {
        await navigator.share({ title: `Performance Report - ${store.storeName}`, text });
      } catch { /* cancelled */ }
    } else {
      await navigator.clipboard.writeText(text);
    }
  };

  const handleWhatsAppReport = () => {
    const text = encodeURIComponent(generateReport());
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  // Breakdown data builders
  const getRevenueBreakdown = () => {
    const map = new Map<string, { name: string; revenue: number; qty: number }>();
    store.sales.forEach(s => {
      const existing = map.get(s.productId) || { name: s.productName, revenue: 0, qty: 0 };
      existing.revenue += s.total;
      existing.qty += s.quantity;
      map.set(s.productId, existing);
    });
    return Array.from(map.values()).sort((a, b) => b.revenue - a.revenue);
  };

  const getProfitBreakdown = () => {
    const map = new Map<string, { name: string; profit: number; margin: number }>();
    store.sales.forEach(s => {
      const product = store.products.find(p => p.id === s.productId);
      const existing = map.get(s.productId) || { name: s.productName, profit: 0, margin: 0 };
      existing.profit += s.profit;
      if (product) existing.margin = Math.round(((product.sellingPrice - product.costPrice) / product.costPrice) * 100);
      map.set(s.productId, existing);
    });
    return Array.from(map.values()).sort((a, b) => b.profit - a.profit);
  };

  const getInventoryBreakdown = () => {
    const restocks = store.restocks || [];
    return [...store.products]
      .map(p => {
        const purchased = restocks
          .filter(r => r.productId === p.id)
          .reduce((sum, r) => sum + r.quantity, 0);
        const initial = p.initialQuantity ?? Math.max(0, p.quantity - purchased);
        return {
          name: p.name,
          category: p.category,
          initial,
          purchased,
          current: p.quantity,
          value: p.costPrice * p.quantity,
        };
      })
      .sort((a, b) => b.value - a.value);
  };

  const getDateRangeBounds = (): { start: Date | null; end: Date | null } => {
    const now = new Date();
    const start = new Date(now);
    start.setHours(0, 0, 0, 0);
    const end = new Date(now);
    end.setHours(23, 59, 59, 999);

    if (salesRange === 'today') return { start, end };
    if (salesRange === 'week') {
      const wkStart = new Date(start);
      wkStart.setDate(start.getDate() - 6);
      return { start: wkStart, end };
    }
    if (salesRange === 'month') {
      const mStart = new Date(start);
      mStart.setDate(start.getDate() - 29);
      return { start: mStart, end };
    }
    if (salesRange === 'custom') {
      const s = customStart ? new Date(customStart + 'T00:00:00') : null;
      const e = customEnd ? new Date(customEnd + 'T23:59:59') : null;
      return { start: s, end: e };
    }
    return { start: null, end: null };
  };

  const filteredSales = useMemo(() => {
    const { start, end } = getDateRangeBounds();
    return store.sales.filter(s => {
      const d = new Date(s.date);
      if (start && d < start) return false;
      if (end && d > end) return false;
      return true;
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [store.sales, salesRange, customStart, customEnd]);

  const getSalesBreakdown = () => {
    const map = new Map<string, { date: string; count: number; total: number; ts: number }>();
    filteredSales.forEach(s => {
      const d = new Date(s.date);
      const dateKey = d.toLocaleDateString();
      const dayTs = new Date(d).setHours(0, 0, 0, 0);
      const existing = map.get(dateKey) || { date: dateKey, count: 0, total: 0, ts: dayTs };
      existing.count += 1;
      existing.total += s.total;
      map.set(dateKey, existing);
    });
    return Array.from(map.values()).sort((a, b) => b.ts - a.ts);
  };

  // Trend chart: last 14 days
  const trendData = useMemo(() => {
    const days = 14;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const buckets: { label: string; total: number; ts: number }[] = [];
    for (let i = days - 1; i >= 0; i--) {
      const d = new Date(today);
      d.setDate(today.getDate() - i);
      buckets.push({
        label: d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }),
        total: 0,
        ts: d.getTime(),
      });
    }
    store.sales.forEach(s => {
      const sd = new Date(s.date);
      sd.setHours(0, 0, 0, 0);
      const bucket = buckets.find(b => b.ts === sd.getTime());
      if (bucket) bucket.total += s.total;
    });
    return buckets;
  }, [store.sales]);

  const cards = [
    { label: 'Revenue', value: `₦${stats.totalRevenue.toLocaleString()}`, color: 'text-primary', type: 'revenue' as BreakdownType },
    { label: 'Profit', value: `₦${stats.totalProfit.toLocaleString()}`, color: 'text-success', type: 'profit' as BreakdownType },
    { label: 'Inventory Value', value: `₦${stats.inventoryValue.toLocaleString()}`, color: 'text-primary', type: 'inventory' as BreakdownType },
    { label: 'Total Sales', value: stats.totalSales.toString(), color: 'text-foreground', type: 'sales' as BreakdownType },
    { label: 'Products', value: stats.totalProducts.toString(), color: 'text-foreground', type: null },
  ];

  return (
    <div className="animate-fade-in space-y-4">
      {/* Share Report Button */}
      <div className="flex gap-2">
        <button
          onClick={handleShareReport}
          className="flex-1 flex items-center justify-center gap-2 p-3 rounded-lg bg-primary/10 border border-primary/20 text-primary font-display font-semibold hover:bg-primary/20 transition-colors text-sm"
        >
          📤 Share Performance Report
        </button>
        <button
          onClick={handleWhatsAppReport}
          className="p-3 rounded-lg bg-success/10 border border-success/20 text-success font-display font-semibold hover:bg-success/20 transition-colors text-sm"
        >
          💬
        </button>
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        {cards.map(c => (
          <button
            key={c.label}
            onClick={() => c.type && toggleBreakdown(c.type)}
            className={`p-4 rounded-xl bg-card border text-left transition-colors ${
              activeBreakdown === c.type && c.type
                ? 'border-primary/50 bg-primary/5'
                : 'border-border hover:border-primary/30'
            }`}
          >
            <p className="text-xs text-muted-foreground mb-1">
              {c.label} {c.type && (activeBreakdown === c.type ? '▲' : '▼')}
            </p>
            <p className={`font-display font-bold text-xl ${c.color}`}>{c.value}</p>
          </button>
        ))}
        <button
          onClick={() => onNavigate('inventory', true)}
          className="p-4 rounded-xl bg-card border border-warning/30 hover:border-warning/60 transition-colors text-left"
        >
          <p className="text-xs text-muted-foreground mb-1">Low Stock ⚠</p>
          <p className="font-display font-bold text-xl text-warning">{stats.lowStockProducts.length}</p>
          <p className="text-[10px] text-muted-foreground mt-1">Tap to view →</p>
        </button>
      </div>

      {/* Breakdown Panel */}
      {activeBreakdown === 'revenue' && (
        <div className="p-4 rounded-xl bg-card border border-border space-y-2 animate-fade-in">
          <h3 className="font-display font-bold text-sm text-primary">Revenue Breakdown</h3>
          {getRevenueBreakdown().length === 0 ? (
            <p className="text-sm text-muted-foreground">No sales yet</p>
          ) : (
            <div className="space-y-1.5 max-h-64 overflow-y-auto">
              {getRevenueBreakdown().map((item, i) => (
                <div key={i} className="flex justify-between items-center p-2 rounded-lg bg-surface-2 text-sm">
                  <div>
                    <span className="text-foreground font-medium">{item.name}</span>
                    <span className="text-muted-foreground ml-2 text-xs">{item.qty} sold</span>
                  </div>
                  <span className="text-primary font-bold">₦{item.revenue.toLocaleString()}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {activeBreakdown === 'profit' && (
        <div className="p-4 rounded-xl bg-card border border-border space-y-2 animate-fade-in">
          <h3 className="font-display font-bold text-sm text-success">Profit Breakdown</h3>
          {getProfitBreakdown().length === 0 ? (
            <p className="text-sm text-muted-foreground">No sales yet</p>
          ) : (
            <div className="space-y-1.5 max-h-64 overflow-y-auto">
              {getProfitBreakdown().map((item, i) => (
                <div key={i} className="flex justify-between items-center p-2 rounded-lg bg-surface-2 text-sm">
                  <div>
                    <span className="text-foreground font-medium">{item.name}</span>
                    <span className="text-muted-foreground ml-2 text-xs">{item.margin}% margin</span>
                  </div>
                  <span className="text-success font-bold">₦{item.profit.toLocaleString()}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {activeBreakdown === 'inventory' && (() => {
        const items = getInventoryBreakdown();
        const totalInitial = items.reduce((s, i) => s + i.initial, 0);
        const totalCurrent = items.reduce((s, i) => s + i.current, 0);
        const totalPurchased = items.reduce((s, i) => s + i.purchased, 0);
        const totalValue = items.reduce((s, i) => s + i.value, 0);
        return (
          <div className="p-4 rounded-xl bg-card border border-border space-y-3 animate-fade-in">
            <h3 className="font-display font-bold text-sm text-primary">Inventory Breakdown</h3>
            <div className="grid grid-cols-3 gap-2">
              <div className="p-2 rounded-lg bg-surface-2 text-center">
                <p className="text-[10px] text-muted-foreground uppercase">Initial</p>
                <p className="font-display font-bold text-base text-foreground">{totalInitial.toLocaleString()}</p>
              </div>
              <div className="p-2 rounded-lg bg-success/10 text-center">
                <p className="text-[10px] text-success uppercase">Bought</p>
                <p className="font-display font-bold text-base text-success">+{totalPurchased.toLocaleString()}</p>
              </div>
              <div className="p-2 rounded-lg bg-primary/10 text-center">
                <p className="text-[10px] text-primary uppercase">Current</p>
                <p className="font-display font-bold text-base text-primary">{totalCurrent.toLocaleString()}</p>
              </div>
            </div>
            <p className="text-[10px] text-muted-foreground text-right">Total value: ₦{totalValue.toLocaleString()}</p>
            <div className="grid grid-cols-4 gap-2 text-[10px] text-muted-foreground px-2 pb-1 border-b border-border uppercase tracking-wide">
              <span className="col-span-1">Product</span>
              <span className="text-center">Initial</span>
              <span className="text-center text-success">+ Bought</span>
              <span className="text-center text-primary">Current</span>
            </div>
            <div className="space-y-1.5 max-h-72 overflow-y-auto">
              {items.map((item, i) => (
                <div key={i} className="grid grid-cols-4 gap-2 items-center p-2 rounded-lg bg-surface-2 text-sm">
                  <div className="col-span-1 min-w-0">
                    <p className="text-foreground font-medium truncate">{item.name}</p>
                    <p className="text-[10px] text-muted-foreground truncate">{item.category} • ₦{item.value.toLocaleString()}</p>
                  </div>
                  <span className="text-center text-muted-foreground">{item.initial}</span>
                  <span className="text-center text-success">{item.purchased > 0 ? `+${item.purchased}` : '—'}</span>
                  <span className={`text-center font-bold ${item.current <= 5 ? 'text-destructive' : 'text-primary'}`}>{item.current}</span>
                </div>
              ))}
            </div>
          </div>
        );
      })()}

      {activeBreakdown === 'sales' && (() => {
        const breakdown = getSalesBreakdown();
        const maxTotal = Math.max(...breakdown.map(d => d.total), 0);
        const minTotal = breakdown.length > 1 ? Math.min(...breakdown.map(d => d.total)) : -1;
        return (
          <div className="p-4 rounded-xl bg-card border border-border space-y-2 animate-fade-in">
            <h3 className="font-display font-bold text-sm">Sales by Day</h3>
            {breakdown.length === 0 ? (
              <p className="text-sm text-muted-foreground">No sales yet</p>
            ) : (
              <>
                {breakdown.length > 1 && (
                  <div className="flex gap-2 text-[10px] text-muted-foreground">
                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-success" /> Best day</span>
                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-destructive" /> Lowest day</span>
                  </div>
                )}
                <div className="space-y-1.5 max-h-72 overflow-y-auto">
                  {breakdown.map((day, i) => {
                    const isBest = day.total === maxTotal && maxTotal > 0;
                    const isWorst = day.total === minTotal && minTotal >= 0 && !isBest;
                    return (
                      <div
                        key={i}
                        className={`flex justify-between items-center p-2 rounded-lg text-sm border ${
                          isBest ? 'bg-success/10 border-success/40' :
                          isWorst ? 'bg-destructive/10 border-destructive/40' :
                          'bg-surface-2 border-transparent'
                        }`}
                      >
                        <div>
                          <span className="text-foreground font-medium">
                            {day.date} {isBest && '🏆'} {isWorst && '📉'}
                          </span>
                          <span className="text-muted-foreground ml-2 text-xs">{day.count} transactions</span>
                        </div>
                        <span className={`font-bold ${isBest ? 'text-success' : isWorst ? 'text-destructive' : 'text-primary'}`}>
                          ₦{day.total.toLocaleString()}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </>
            )}
          </div>
        );
      })()}

      {topSellers.length > 0 && (
        <div className="p-4 rounded-xl bg-card border border-border">
          <h3 className="font-display font-bold mb-3">Top Sellers</h3>
          <div className="h-[200px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={topSellers} layout="vertical" margin={{ left: 0, right: 10 }}>
                <XAxis type="number" tick={{ fill: 'hsl(240 5% 50%)', fontSize: 11 }} />
                <YAxis
                  type="category"
                  dataKey="name"
                  width={120}
                  tick={{ fill: 'hsl(45 5% 85%)', fontSize: 11 }}
                />
                <Tooltip
                  contentStyle={{ background: 'hsl(240 10% 10%)', border: '1px solid hsl(240 8% 18%)', borderRadius: 8, fontSize: 12 }}
                  labelStyle={{ color: 'hsl(45 90% 61%)' }}
                  formatter={(value: number) => [`${value} units`, 'Sold']}
                />
                <Bar dataKey="totalSold" fill="hsl(45, 90%, 61%)" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}
    </div>
  );
}