import { useEffect, useRef, useState } from 'react';
import { Camera, X, RotateCcw } from 'lucide-react';
import { useBodyScrollLock } from '@/hooks/use-body-scroll-lock';

interface Props { onCapture: (file: File) => void; onClose: () => void; }

export default function FlowCameraCapture({ onCapture, onClose }: Props) {
  // Overlay: hold the page behind it still while this is open.
  useBodyScrollLock();
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const [error, setError] = useState(''); const [facing, setFacing] = useState<'environment' | 'user'>('environment');
  useEffect(() => { let active = true; const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: facing }, width: { ideal: 1920 }, height: { ideal: 1080 }, frameRate: { ideal: 30, max: 60 } }, audio: false }); if (!active) { stream.getTracks().forEach(t => t.stop()); return; } streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } } catch { setError('Camera permission was denied or the camera is unavailable.'); } }; start(); return () => { active = false; streamRef.current?.getTracks().forEach(t => t.stop()); streamRef.current = null; }; }, [facing]);
  const close = () => { streamRef.current?.getTracks().forEach(t => t.stop()); streamRef.current = null; onClose(); };
  const capture = async () => { const track = streamRef.current?.getVideoTracks()[0]; if (!track) return; let blob: Blob | null = null; try { const ImageCaptureCtor = (window as any).ImageCapture; if (ImageCaptureCtor) { const photo = await new ImageCaptureCtor(track).takePhoto(); if (photo) blob = photo; } } catch { /* fall back to the live preview frame */ } if (!blob) { const video = videoRef.current; if (!video || !video.videoWidth) return; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0, canvas.width, canvas.height); blob = await new Promise<Blob | null>(r => canvas.toBlob(r, 'image/jpeg', .95)); } if (!blob) return; onCapture(new File([blob], `flow-camera-${Date.now()}.jpg`, { type: 'image/jpeg' })); close(); };
  return <div className="fixed inset-0 z-[90] bg-black flex flex-col"><div className="flex items-center justify-between p-4 text-white"><b className="font-display">Flow Camera</b><button onClick={close} className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center"><X /></button></div><div className="flex-1 flex items-center justify-center p-4"><div className="w-full max-w-lg overflow-hidden rounded-3xl bg-black border border-white/10 relative"><video ref={videoRef} playsInline muted className="w-full aspect-[3/4] object-cover" />{error && <div className="absolute inset-0 flex items-center justify-center p-8 text-center text-sm text-white bg-black/70">{error}</div>}</div></div><div className="p-6 flex items-center justify-center gap-8"><button onClick={() => setFacing(v => v === 'environment' ? 'user' : 'environment')} className="w-12 h-12 rounded-full bg-white/10 text-white flex items-center justify-center"><RotateCcw /></button><button onClick={capture} disabled={!!error} className="w-20 h-20 rounded-full bg-white border-4 border-white/40 flex items-center justify-center disabled:opacity-40"><Camera className="text-black w-8 h-8" /></button><div className="w-12" /></div></div>;
}
